### ISSUE TITLE
renaming the Go module name to `github.com/rog-golang-buddies/rapidmidiex`

### ISSUE THREAD

**Issue by adoublef** [rog-golang-buddies/rapidmidiex#7]
I noticed [here](https://github.com/rog-golang-buddies/rapidmidiex/blob/1afafac469938eb4c59fa769dffeb0fa570e563e/go.mod#L1) that the Go module is going to cause issues given its not the same as the repo url but the organisation name, this could cause conflicts later on, can this be fixed?

**Comment by pmoieni** [comment]
@adoublef fixed. Changed it to `github.com/rog-golang-buddies/rapidmidiex`
